UPDATE stores SET address = 'Trụ sở Ủy ban Nhân dân TP. Hồ Chí Minh, 86, Lê Thánh Tôn, Khu phố 5, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 1;
UPDATE stores SET address = 'Bưu điện Trung tâm Sài Gòn, 2, Công trường Công xã Paris, Khu phố 3, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 2;
UPDATE stores SET address = 'Đại chủng viện thánh Giuse, 6, Tôn Đức Thắng, Khu phố 1, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 3;
UPDATE stores SET address = 'Sàn Art, Hẻm 48 Mê Linh, Thạnh Mỹ Tây, Phường Thạnh Mỹ Tây, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 4;
UPDATE stores SET address = 'Trụ sở Ủy ban Nhân dân TP. Hồ Chí Minh, 86, Lê Thánh Tôn, Khu phố 5, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 5;
UPDATE stores SET address = 'Bưu điện Trung tâm Sài Gòn, 2, Công trường Công xã Paris, Khu phố 3, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 6;
UPDATE stores SET address = 'Đại chủng viện thánh Giuse, 6, Tôn Đức Thắng, Khu phố 1, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 7;
UPDATE stores SET address = 'Sàn Art, Hẻm 48 Mê Linh, Thạnh Mỹ Tây, Phường Thạnh Mỹ Tây, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 8;
UPDATE stores SET address = 'Trụ sở Ủy ban Nhân dân TP. Hồ Chí Minh, 86, Lê Thánh Tôn, Khu phố 5, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 9;
UPDATE stores SET address = 'Bưu điện Trung tâm Sài Gòn, 2, Công trường Công xã Paris, Khu phố 3, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 10;
UPDATE stores SET address = 'Đại chủng viện thánh Giuse, 6, Tôn Đức Thắng, Khu phố 1, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 11;
UPDATE stores SET address = 'Sàn Art, Hẻm 48 Mê Linh, Thạnh Mỹ Tây, Phường Thạnh Mỹ Tây, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 12;
UPDATE stores SET address = 'Trụ sở Ủy ban Nhân dân TP. Hồ Chí Minh, 86, Lê Thánh Tôn, Khu phố 5, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 13;
UPDATE stores SET address = 'Trụ sở Ủy ban Nhân dân TP. Hồ Chí Minh, 86, Lê Thánh Tôn, Khu phố 5, Phường Sài Gòn, Thủ Đức, Thành phố Hồ Chí Minh, 71006, Việt Nam' WHERE id = 14;
UPDATE stores SET address = '73, Đường số 8, Thông Hội Tây, Phường Thông Tây Hội, Thành phố Hồ Chí Minh, 71500, Việt Nam' WHERE id = 15;
UPDATE stores SET address = 'Xã Bình Lợi, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 16;
UPDATE stores SET address = 'Samsung CE Ho Chi Minh City Complex, Đường D12, Phường Tăng Nhơn Phú, Thành phố Hồ Chí Minh, 71350, Việt Nam' WHERE id = 17;
UPDATE stores SET address = 'Đường N1, Đông A, Phường Đông Hòa, Thành phố Hồ Chí Minh, 75207, Việt Nam' WHERE id = 18;
UPDATE stores SET address = 'Phước Hòa, Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 57100, Việt Nam' WHERE id = 19;
UPDATE stores SET address = 'Trường Tiểu học Vinschool The Harmony, Phố Đào Hinh, Vinhomes Riverside, Phường Việt Hưng, Phường Phúc Lợi, Thành phố Hà Nội, 08443, Việt Nam' WHERE id = 20;
UPDATE stores SET address = 'Xã An Khánh, Thành phố Hà Nội, 01234, Việt Nam' WHERE id = 21;
UPDATE stores SET address = 'Xương Cá 2, Xã Bình Hưng, Thành phố Hồ Chí Minh, 71812, Việt Nam' WHERE id = 22;
UPDATE stores SET address = 'Ngách 28 Ngõ Văn Hương, Phường Văn Miếu – Quốc Tử Giám, Quận Đống Đa, Thành phố Hà Nội, 10081, Việt Nam' WHERE id = 23;
UPDATE stores SET address = 'Ngách 254/101 Phố Minh Khai, Phường Tương Mai, Quận Hoàng Mai, Thành phố Hà Nội, 11617, Việt Nam' WHERE id = 24;
UPDATE stores SET address = 'Xã Song Phú, Tỉnh Vĩnh Long, Việt Nam' WHERE id = 25;
UPDATE stores SET address = 'Xã Bà Nà, Thành phố Đà Nẵng, Việt Nam' WHERE id = 26;
UPDATE stores SET address = 'Đường Số 1, Khu phố 25, Phường Bình Trưng, Thành phố Hồ Chí Minh, 71108, Việt Nam' WHERE id = 27;
UPDATE stores SET address = 'Hoa Phượng 3, Vinhomes Riverside, Phúc Lợi, Quận Long Biên, Thành phố Hà Nội, 08443, Việt Nam' WHERE id = 28;
UPDATE stores SET address = 'Chợ Dĩ An, Nguyễn An Ninh, Đông Tân, Phường Dĩ An, Thành phố Hồ Chí Minh, 75207, Việt Nam' WHERE id = 29;
UPDATE stores SET address = 'Sân Golf Tân Sơn Nhất, Tân Sơn, An Hội Tây, Phường An Hội Tây, Thành phố Hồ Chí Minh, 71500, Việt Nam' WHERE id = 30;
UPDATE stores SET address = 'Quốc lộ 54, Phường Bình Minh, Tỉnh Vĩnh Long, 94111, Việt Nam' WHERE id = 31;
UPDATE stores SET address = 'Phường Hòa Khánh, Thành phố Đà Nẵng, 51000, Việt Nam' WHERE id = 32;
UPDATE stores SET address = 'Đường Số 14, Phường Đông Hưng Thuận, Thành phố Hồ Chí Minh, 71509, Việt Nam' WHERE id = 33;
UPDATE stores SET address = 'Hội An, Thành phố Đà Nẵng, 64000, Việt Nam' WHERE id = 34;
UPDATE stores SET address = 'Tạ Thị Phi, Quận Bình Thủy, Thành phố Cần Thơ, 94000, Việt Nam' WHERE id = 35;
UPDATE stores SET address = 'Đường Đỗ Mười, Lĩnh Nam, Quận Hoàng Mai, Thành phố Hà Nội, 11622, Việt Nam' WHERE id = 36;
UPDATE stores SET address = 'Xã Phúc Thịnh, Thành phố Hà Nội, Việt Nam' WHERE id = 37;
UPDATE stores SET address = 'Trần Phú, Vĩnh Nguyên, Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 57131, Việt Nam' WHERE id = 38;
UPDATE stores SET address = 'ĐT. 917, Phường Thới An Đông, Thành phố Cần Thơ, Việt Nam' WHERE id = 39;
UPDATE stores SET address = 'Xã Tân Phú Trung, Tỉnh Đồng Tháp, 90000, Việt Nam' WHERE id = 40;
UPDATE stores SET address = 'KCN Nam Thuận, Xã Mỹ Hạnh, Tỉnh Tây Ninh, Việt Nam' WHERE id = 41;
UPDATE stores SET address = 'Phường Bắc Nha Trang, Tỉnh Khánh Hòa, Việt Nam' WHERE id = 42;
UPDATE stores SET address = 'Xã Bình Mỹ, Thành phố Hồ Chí Minh, 75106, Việt Nam' WHERE id = 43;
UPDATE stores SET address = 'Đường Số 24A, Đức Hòa, Xã Đức Hòa, Tỉnh Tây Ninh, Việt Nam' WHERE id = 44;
UPDATE stores SET address = 'Trung tâm Văn hóa Thể thao Tân Bình, Hoàng Văn Thụ, Tân Bình, Phường Tân Sơn Nhất, Thành phố Hồ Chí Minh, 72106, Việt Nam' WHERE id = 45;
UPDATE stores SET address = 'Xã Diên Điền, Tỉnh Khánh Hòa, Việt Nam' WHERE id = 46;
UPDATE stores SET address = 'Lê Bá Trinh, Xã Tân Nhựt, Thành phố Hồ Chí Minh, 71959, Việt Nam' WHERE id = 47;
UPDATE stores SET address = 'Cầu Phù Đổng, Đường cao tốc Hà Nội - Bắc Giang, Phường Phúc Lợi, Thành phố Hà Nội, 08443, Việt Nam' WHERE id = 48;
UPDATE stores SET address = 'Thanh Tương, Phường Trí Quả, Từ Sơn, Tỉnh Bắc Ninh, Việt Nam' WHERE id = 49;
UPDATE stores SET address = 'Xã Thư Lâm, Thành phố Hà Nội, Việt Nam' WHERE id = 50;
UPDATE stores SET address = 'Vĩnh Thọ, Phường Bắc Nha Trang, Tỉnh Khánh Hòa, 57100, Việt Nam' WHERE id = 51;
UPDATE stores SET address = 'Xã Song Phú, Tỉnh Vĩnh Long, Việt Nam' WHERE id = 52;
UPDATE stores SET address = 'Xã Phúc Thịnh, Thành phố Hà Nội, 12323, Việt Nam' WHERE id = 53;
UPDATE stores SET address = 'Quận Ô Môn, Thành phố Cần Thơ, Việt Nam' WHERE id = 54;
UPDATE stores SET address = 'Xã An Lão, Thành phố Hải Phòng, Huyện An Lão, 35999, Việt Nam' WHERE id = 55;
UPDATE stores SET address = 'Xã Cam Lâm, Tỉnh Khánh Hòa, 57600, Việt Nam' WHERE id = 56;
UPDATE stores SET address = 'Đường tỉnh 743C, Đồng An 3, Phường Bình Hòa, Thành phố Hồ Chí Minh, 75207, Việt Nam' WHERE id = 57;
UPDATE stores SET address = 'Hội An, Thành phố Đà Nẵng, 64000, Việt Nam' WHERE id = 58;
UPDATE stores SET address = 'Đường tỉnh 363, Xã Kiến Minh, Thành phố Hải Phòng, Huyện Kiến Thụy, Việt Nam' WHERE id = 59;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 60;
UPDATE stores SET address = 'Vĩnh Phú 6, Đông, Khu phố Đông, Phường Bình Hòa, Thành phố Hồ Chí Minh, 70000, Việt Nam' WHERE id = 61;
UPDATE stores SET address = 'Royal Lotus Hotel, 120, Đường Lê Quang Đạo, Phường An Hải, Phường Ngũ Hành Sơn, Thành phố Đà Nẵng, 50507, Việt Nam' WHERE id = 62;
UPDATE stores SET address = 'Trấn Đại Nghĩa, Xã Bình Lợi, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 63;
UPDATE stores SET address = 'Hẻm 410 Lê Quang Đinh, Bình Lợi Trung, Phường Bình Lợi Trung, Thành phố Hồ Chí Minh, 72317, Việt Nam' WHERE id = 64;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 65;
UPDATE stores SET address = 'Vĩnh Nguyên, Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 57131, Việt Nam' WHERE id = 66;
UPDATE stores SET address = 'Xã Thư Lâm, Thành phố Hà Nội, Việt Nam' WHERE id = 67;
UPDATE stores SET address = 'Khu công nghiệp Vĩnh Lộc, Phường Bình Tân, Thành phố Hồ Chí Minh, 71914, Việt Nam' WHERE id = 68;
UPDATE stores SET address = 'Bảo Hiểm Bảo Việt, 65, Thống Nhất, Khu phố 2, Phường Thủ Đức, Thành phố Hồ Chí Minh, 71221, Việt Nam' WHERE id = 69;
UPDATE stores SET address = 'Main Street, Khu đô thị Nam Thăng Long, Phường Xuân Đỉnh, Quận Bắc Từ Liêm, Thành phố Hà Nội, 10264, Việt Nam' WHERE id = 70;
UPDATE stores SET address = 'Phường Long Trường, Thành phố Hồ Chí Minh, 08408, Việt Nam' WHERE id = 71;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 72;
UPDATE stores SET address = 'Phố Lâm Tường, Phường Lê Chân, Quận Lê Chân, Thành phố Hải Phòng, 18000, Việt Nam' WHERE id = 73;
UPDATE stores SET address = 'Đường Như Nguyệt, Phường Hải Châu, Quận Hải Châu, Thành phố Đà Nẵng, 50207, Việt Nam' WHERE id = 74;
UPDATE stores SET address = 'Xã Trường Long, Thành phố Cần Thơ, Việt Nam' WHERE id = 75;
UPDATE stores SET address = 'Phường Bình Minh, Tỉnh Vĩnh Long, 94111, Việt Nam' WHERE id = 76;
UPDATE stores SET address = 'Tỉnh lộ 15, Xã Phú Hòa Đông, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 77;
UPDATE stores SET address = 'Chử Xá, Xã Bát Tràng, Thành phố Hà Nội, Việt Nam' WHERE id = 78;
UPDATE stores SET address = 'Hẻm 18 Tăng Bạt Hổ, Bình Lợi Trung, Phường Bình Lợi Trung, Thành phố Hồ Chí Minh, 72317, Việt Nam' WHERE id = 79;
UPDATE stores SET address = 'Kho Viettel Z11, Khu Z11, Đỗ Mười, Trung Mỹ Tây, Phường Trung Mỹ Tây, Thành phố Hồ Chí Minh, 71507, Việt Nam' WHERE id = 80;
UPDATE stores SET address = 'Phường Bình Đông, Thành phố Hồ Chí Minh, 71959, Việt Nam' WHERE id = 81;
UPDATE stores SET address = 'Đường Tiền Lân 15, Xã Bà Điểm, Thành phố Hồ Chí Minh, 71914, Việt Nam' WHERE id = 82;
UPDATE stores SET address = 'Khu biệt thự Thiên đường Bảo Sơn, Trường An, Xã An Khánh, Thành phố Hà Nội, 34000, Việt Nam' WHERE id = 83;
UPDATE stores SET address = 'Xã Hùng Thắng, Thành phố Hải Phòng, Huyện Tiên Lãng, Việt Nam' WHERE id = 84;
UPDATE stores SET address = 'Đường Dương Thị Thiệt, Xã Hưng Long, Thành phố Hồ Chí Minh, 71812, Việt Nam' WHERE id = 85;
UPDATE stores SET address = 'Xã Vĩnh Lộc, Thành phố Hồ Chí Minh, 71821, Việt Nam' WHERE id = 86;
UPDATE stores SET address = 'Xã Vĩnh Thanh, Thành phố Hà Nội, 12323, Việt Nam' WHERE id = 87;
UPDATE stores SET address = 'Khu Công nghiệp An Hạ, Xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 88;
UPDATE stores SET address = 'Xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh, 71913, Việt Nam' WHERE id = 89;
UPDATE stores SET address = 'Phước Hòa, Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 57100, Việt Nam' WHERE id = 90;
UPDATE stores SET address = 'Ngách 69 Ngõ Thống Nhất, Thống Nhất, Quận Long Biên, Thành phố Hà Nội, 08443, Việt Nam' WHERE id = 91;
UPDATE stores SET address = 'Xã Đông Anh, Thành phố Hà Nội, 12323, Việt Nam' WHERE id = 92;
UPDATE stores SET address = 'Đường D1, Khu phố Bình Phú, Phường Thuận Giao, Thành phố Hồ Chí Minh, 75000, Việt Nam' WHERE id = 93;
UPDATE stores SET address = 'Hội An, Thành phố Đà Nẵng, 64000, Việt Nam' WHERE id = 94;
UPDATE stores SET address = 'Xã Củ Chi, Thành phố Hồ Chí Minh, 71608, Việt Nam' WHERE id = 95;
UPDATE stores SET address = 'An Lạc, Xã Gia Lâm, Thành phố Hà Nội, 08443, Việt Nam' WHERE id = 96;
UPDATE stores SET address = 'Đường Lý Phục Man, Xã Sơn Đồng, Thành phố Hà Nội, 34000, Việt Nam' WHERE id = 97;
UPDATE stores SET address = 'Hẻm 1004 Hương lộ 2, Phường Bình Trị Đông, Thành phố Hồ Chí Minh, 72031, Việt Nam' WHERE id = 98;
UPDATE stores SET address = 'Hẻm 63 Nguyễn Thị Thập, Phường Tân Mỹ, Thành phố Hồ Chí Minh, 71800, Việt Nam' WHERE id = 99;
UPDATE stores SET address = 'Phường Thủy Nguyên, Thành phố Hải Phòng, 04813, Việt Nam' WHERE id = 100;
UPDATE stores SET address = 'Đông Ngạc, Phường Đông Ngạc, Quận Bắc Từ Liêm, Thành phố Hà Nội, 12500, Việt Nam' WHERE id = 101;
UPDATE stores SET address = 'Vĩnh Ngọc, Phường Tây Nha Trang, Tỉnh Khánh Hòa, 57124, Việt Nam' WHERE id = 102;
UPDATE stores SET address = 'Phố Đằng Hải, Phường Hải An, Quận Hải An, Thành phố Hải Phòng, 04813, Việt Nam' WHERE id = 103;
UPDATE stores SET address = 'Xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 104;
UPDATE stores SET address = 'Đường Hoa Hồng 4, Phường An Hải, Quận Sơn Trà, Thành phố Đà Nẵng, 02363, Việt Nam' WHERE id = 105;
UPDATE stores SET address = 'Ngách 18 Ngõ 165 Đường Cầu Giấy, Phường Cầu Giấy, Quận Cầu Giấy, Thành phố Hà Nội, 10198, Việt Nam' WHERE id = 106;
UPDATE stores SET address = 'Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 48058, Việt Nam' WHERE id = 107;
UPDATE stores SET address = 'Phòng Giao dịch số 11 - Kho bạc Nhà nước khu vực I, Đường tỉnh 301, Xã Phúc Thịnh, Thành phố Hà Nội, 12323, Việt Nam' WHERE id = 108;
UPDATE stores SET address = 'Tân Phú 2, Phường Tân Đông Hiệp, Thành phố Hồ Chí Minh, 75209, Việt Nam' WHERE id = 109;
UPDATE stores SET address = 'Xã Trường Thành, Thành phố Cần Thơ, Việt Nam' WHERE id = 110;
UPDATE stores SET address = 'Xã Trường Long, Thành phố Cần Thơ, Việt Nam' WHERE id = 111;
UPDATE stores SET address = 'Trung Mỹ Tây, Phường Trung Mỹ Tây, Thành phố Hồ Chí Minh, 71507, Việt Nam' WHERE id = 112;
UPDATE stores SET address = 'Phường Hải An, Quận Hải An, Thành phố Hải Phòng, 04813, Việt Nam' WHERE id = 113;
UPDATE stores SET address = 'Quốc lộ 1, Vĩnh Phương, Phường Bắc Nha Trang, Tỉnh Khánh Hòa, Việt Nam' WHERE id = 114;
UPDATE stores SET address = 'Xã Đông Anh, Thành phố Hà Nội, 11810, Việt Nam' WHERE id = 115;
UPDATE stores SET address = 'Phường Ô Môn, Thành phố Cần Thơ, Việt Nam' WHERE id = 116;
UPDATE stores SET address = 'Xã Bát Tràng, Văn Giang, Tỉnh Hưng Yên, Việt Nam' WHERE id = 117;
UPDATE stores SET address = 'Xã Đông Thạnh, Thành phố Hồ Chí Minh, 71514, Việt Nam' WHERE id = 118;
UPDATE stores SET address = '9A, Vũ Ngọc Phan, Bình Lợi Trung, Phường Bình Lợi Trung, Thành phố Hồ Chí Minh, 72309, Việt Nam' WHERE id = 119;
UPDATE stores SET address = 'Phường Nam Nha Trang, Tỉnh Khánh Hòa, Việt Nam' WHERE id = 120;
UPDATE stores SET address = 'Xã Suối Dầu, Tỉnh Khánh Hòa, Việt Nam' WHERE id = 121;
UPDATE stores SET address = 'Đường số 6, Khu công nghiệp Vĩnh Lộc, Xã Vĩnh Lộc, Thành phố Hồ Chí Minh, 71914, Việt Nam' WHERE id = 122;
UPDATE stores SET address = 'Hẻm 539A Bình Thới, Bình Thới, Phường Bình Thới, Thành phố Hồ Chí Minh, 72015, Việt Nam' WHERE id = 123;
UPDATE stores SET address = 'Tân Thới Nhất 8, Đông Hưng Thuận, Phường Đông Hưng Thuận, Thành phố Hồ Chí Minh, 71914, Việt Nam' WHERE id = 124;
UPDATE stores SET address = 'Đường X1, Khu phố 2, Phường An Phú, Thành phố Hồ Chí Minh, 75209, Việt Nam' WHERE id = 125;
UPDATE stores SET address = 'Cách Mạng Tháng 8, Phường Cái Khế, Thành phố Cần Thơ, 94108, Việt Nam' WHERE id = 126;
UPDATE stores SET address = 'Phường Thủy Nguyên, Thành phố Hải Phòng, 04813, Việt Nam' WHERE id = 127;
UPDATE stores SET address = 'Hẻm 13 Trần Mai Ninh, Phường Bảy Hiền, Thành phố Hồ Chí Minh, 72106, Việt Nam' WHERE id = 128;
UPDATE stores SET address = 'Ecopark, Phụng Công, Tỉnh Hưng Yên, Việt Nam' WHERE id = 129;
UPDATE stores SET address = 'Xã Bình Lợi, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 130;
UPDATE stores SET address = 'Đê tả Sông Hồng, Xã Mê Linh, Thành phố Hà Nội, 12910, Việt Nam' WHERE id = 131;
UPDATE stores SET address = 'Vĩnh Thái, Phường Nam Nha Trang, Tỉnh Khánh Hòa, 57124, Việt Nam' WHERE id = 132;
UPDATE stores SET address = 'Đền Tưởng niệm Di tích Bến Nọc, Đường N2, Khu công nghệ cao Thành phố Hồ Chí Minh, Phường Tăng Nhơn Phú, Thành phố Hồ Chí Minh, 71300, Việt Nam' WHERE id = 133;
UPDATE stores SET address = 'Xã Tân Nhựt, Thành phố Hồ Chí Minh, 71959, Việt Nam' WHERE id = 134;
UPDATE stores SET address = 'Vĩnh Nguyên, Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 57131, Việt Nam' WHERE id = 135;
UPDATE stores SET address = 'Sân bay quốc tế Đà Nẵng, Đường Nguyên Hồng, Phường Thanh Khê, Quận Thanh Khê, Thành phố Đà Nẵng, 84236, Việt Nam' WHERE id = 136;
UPDATE stores SET address = 'Phường Thuận An, Thành phố Hồ Chí Minh, 75214, Việt Nam' WHERE id = 137;
UPDATE stores SET address = 'Đường Hói Kiểng 17, Quận Ngũ Hành Sơn, Thành phố Đà Nẵng, 50507, Việt Nam' WHERE id = 138;
UPDATE stores SET address = 'Phường Điện Bàn Tây, Thành phố Đà Nẵng, Việt Nam' WHERE id = 139;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 140;
UPDATE stores SET address = 'Trường THCS Tây Tựu, Ngõ 192 Đường Tây Tựu, Tây Tựu, Quận Bắc Từ Liêm, Thành phố Hà Nội, 34000, Việt Nam' WHERE id = 141;
UPDATE stores SET address = 'Phường Thượng Cát, Quận Bắc Từ Liêm, Thành phố Hà Nội, Việt Nam' WHERE id = 142;
UPDATE stores SET address = 'Phố Phạm Khắc Hòe, Khu đô thị Dương Nội, Dương Nội, Quận Hà Đông, Thành phố Hà Nội, 10189, Việt Nam' WHERE id = 143;
UPDATE stores SET address = 'Đường Tân Thạnh, Diamond Alnata, Phường Tân Sơn Nhì, Thành phố Hồ Chí Minh, 71913, Việt Nam' WHERE id = 144;
UPDATE stores SET address = 'Nguyễn Văn Thuần, Cộng Hòa, Phường Hiệp Hòa, Tỉnh Quảng Ninh, Việt Nam' WHERE id = 145;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 146;
UPDATE stores SET address = 'Khu phố 2, Phường Thủ Dầu Một, Thành phố Hồ Chí Minh, 75107, Việt Nam' WHERE id = 147;
UPDATE stores SET address = 'WinMart+, Đường Eco Lake View, Phường Định Công, Quận Hoàng Mai, Thành phố Hà Nội, 11718, Việt Nam' WHERE id = 148;
UPDATE stores SET address = 'Xã Tân Lược, Tỉnh Vĩnh Long, Việt Nam' WHERE id = 149;
UPDATE stores SET address = 'Nha Trang, Phường Nha Trang, Tỉnh Khánh Hòa, 48058, Việt Nam' WHERE id = 150;
UPDATE stores SET address = 'Xã Bình Lợi, Thành phố Hồ Chí Minh, Việt Nam' WHERE id = 151;
UPDATE stores SET address = 'Xã Đông Anh, Thành phố Hà Nội, 12323, Việt Nam' WHERE id = 152;
UPDATE stores SET address = 'Thành phố Đà Nẵng, Việt Nam' WHERE id = 153;
UPDATE stores SET address = 'Xã Vĩnh Lộc, Thành phố Hồ Chí Minh, 71821, Việt Nam' WHERE id = 154;
UPDATE stores SET address = 'Xã Bà Điểm, Thành phố Hồ Chí Minh, 71717, Việt Nam' WHERE id = 155;
UPDATE stores SET address = 'Hẻm 28 Đường M1, Phường Bình Hưng Hòa, Thành phố Hồ Chí Minh, 71914, Việt Nam' WHERE id = 156;
UPDATE stores SET address = 'Phường Bình Đông, Thành phố Hồ Chí Minh, 71959, Việt Nam' WHERE id = 157;
UPDATE stores SET address = 'Phường Hải Vân, Thành phố Đà Nẵng, Xã Chân Mây - Lăng Cô, Thành phố Huế, Việt Nam' WHERE id = 158;
UPDATE stores SET address = 'Hẻm 382 Nguyễn Thái Sơn, An Nhơn, Phường An Nhơn, Thành phố Hồ Chí Minh, 71400, Việt Nam' WHERE id = 159;
UPDATE stores SET address = 'Xã Bà Điểm, Thành phố Hồ Chí Minh, 71717, Việt Nam' WHERE id = 160;
UPDATE stores SET address = 'Xã Sóc Sơn, Thành phố Hà Nội, Việt Nam' WHERE id = 161;
UPDATE stores SET address = 'Nguyễn Triệu Luật, Phường Bình Tân, Thành phố Hồ Chí Minh, 73118, Việt Nam' WHERE id = 162;
UPDATE stores SET address = 'Thành phố Hà Nội, 10000, Việt Nam' WHERE id = 163;
UPDATE stores SET address = '44, N, Phường Khánh Hội, Thành phố Hồ Chí Minh, 72800, Việt Nam' WHERE id = 164;